
#[exit_status::main]
fn main() -> std::result::Result<i32, Box<dyn std::error::Error>> {
    Ok(0)
}